Customer.create!(name: "Finkakor AB", adress: "Helsingborg")
Customer.create!(name: "Småbröd AB", adress: "Malmö")
Customer.create!(name: "Kaffebröd AB", adress: "Landskrona")
Customer.create!(name: "Bjudkakor AB", adress: "Ystad")
Customer.create!(name: "Kalaskakor AB", adress: "Trellebrg")
Customer.create!(name: "Partykakor AB", adress: "Kristianstad")
Customer.create!(name: "Gästkakor AB", adress: "Hässleholm")
Customer.create!(name: "Skånekakor AB", adress: "Perstorp")

Ingredient.create!(name: "Flour")
Ingredient.create!(name: "Butter")
Ingredient.create!(name: "Icing sugar")
Ingredient.create!(name: "Roasted, chopped nuts")
Ingredient.create!(name: "Fine-ground nuts")
Ingredient.create!(name: "Ground, roasted nuts")
Ingredient.create!(name: "Bread crumbs")
Ingredient.create!(name: "Sugar")
Ingredient.create!(name: "Egg whites")
Ingredient.create!(name: "Chocolate")
Ingredient.create!(name: "Marzipan")
Ingredient.create!(name: "Butter")
Ingredient.create!(name: "Eggs")
Ingredient.create!(name: "Potato starch")
Ingredient.create!(name: "Wheat flour")
Ingredient.create!(name: "Sodium bicarbonate")
Ingredient.create!(name: "Vanilla")
Ingredient.create!(name: "Chopped almonds")
Ingredient.create!(name: "Cinnamon")
Ingredient.create!(name: "Icing sugar")
Ingredient.create!(name: "Vanilla sugar")

c1 = Cookie.create!(name: "Nut ring")
c1.build_recipe((Ingredient.find_by name: "Flour"), 450)
c1.build_recipe((Ingredient.find_by name: "Butter"), 450 )
c1.build_recipe((Ingredient.find_by name: "Icing sugar"), 190)
c1.build_recipe((Ingredient.find_by name: "Roasted, chopped nuts"), 225 )

c2 = Cookie.create!(name: "Nut cookie")
c2.build_recipe((Ingredient.find_by name: "Fine-ground nuts"), 750 )
c2.build_recipe((Ingredient.find_by name: "Ground, roasted nuts"), 625 )
c2.build_recipe((Ingredient.find_by name: "Bread crumbs"), 125 )
c2.build_recipe((Ingredient.find_by name: "Sugar"), 375 )
c2.build_recipe((Ingredient.find_by name: "Egg whites"), 3.5 )
c2.build_recipe((Ingredient.find_by name: "Chocolate"), 50 )

c3 = Cookie.create!(name: "Amneris")
c3.build_recipe((Ingredient.find_by name: "Marzipan"), 750 )
c3.build_recipe((Ingredient.find_by name: "Butter"), 250 )
c3.build_recipe((Ingredient.find_by name: "Eggs"), 250 )
c3.build_recipe((Ingredient.find_by name: "Potato starch"), 25 )
c3.build_recipe((Ingredient.find_by name: "Wheat flour"), 25 )

c4 = Cookie.create!(name: "Tango")
c4.build_recipe((Ingredient.find_by name: "Butter"), 200 )
c4.build_recipe((Ingredient.find_by name: "Sugar"), 250 )
c4.build_recipe((Ingredient.find_by name: "Flour"), 300 )
c4.build_recipe((Ingredient.find_by name: "Sodium bicarbonate"), 4 )
c4.build_recipe((Ingredient.find_by name: "Vanilla"), 2 )

c5 = Cookie.create!(name: "Almond delight")
c5.build_recipe((Ingredient.find_by name: "Butter"), 400 )
c5.build_recipe((Ingredient.find_by name: "Sugar"), 270 )
c5.build_recipe((Ingredient.find_by name: "Chopped almonds"), 270 )
c5.build_recipe((Ingredient.find_by name: "Flour"), 400 )
c5.build_recipe((Ingredient.find_by name: "Cinnamon"), 10 )

c6 = Cookie.create!(name: "Berliner")
c6.build_recipe((Ingredient.find_by name: "Flour"), 350 )
c6.build_recipe((Ingredient.find_by name: "Butter"), 250 )
c6.build_recipe((Ingredient.find_by name: "Icing sugar"), 100 )
c6.build_recipe((Ingredient.find_by name: "Eggs"), 50 )
c6.build_recipe((Ingredient.find_by name: "Vanilla sugar"), 5 )
c6.build_recipe((Ingredient.find_by name: "Chocolate"), 50 )

